### ISSUE TITLE
Create a cheatsheet both Earth Engine API and rgee

### ISSUE THREAD

**Issue by csaybar** [csaybar/rgee#33]

**Comment by jdbcode** [comment]
Inspiration - I've always liked this cheatsheet a lot: https://rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf

**Comment by csaybar** [comment]
@barja8 you have work here :D

**Comment by barja8** [comment]
@csaybar you are right! In this week I will work every day on this cheatsheet, I am more motivated than ever :3

**Comment by csaybar** [comment]
Closed until further notice
