### ISSUE TITLE
TypeError: get_authorization_url()

### ISSUE THREAD

**Issue by GReimche** [csaybar/rgee#38]
Hi Aybar,
Could you please advice me in the following error I'm getting by running

      ee_Initialize(email = "my email", drive = TRUE, gcs = FALSE)

I get the following error:

     -- rgee 0.3.0 --------------------------------------- earthengine-api 0.1.216 --

 √ email: xxx@gmail.com 
 √ Google Drive credentials:  FOUND
 √ Initializing Google Earth Engine:Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: get_authorization_url() missing 1 required positional argument: 'code_challenge

By running:
> ee_get_earthengine_path()  I get the following:

Error in ee_get_earthengine_path() :  rgee_sessioninfo.txt does not exist, run rgee::ee_Initialize() to fixed.
There is no " rgee_sessioninfo.txt " folder in the .config/earthengine/user.

Observations:
- Python API earthengine is installed

- No files if:
ee_path <- path.expand("~/.config/earthengine/credentials")

- > py_config()
python:         C:/ProgramData/Miniconda3/envs/ee/python.exe
libpython:      C:/ProgramData/Miniconda3/envs/ee/python37.dll
pythonhome:     C:/ProgramData/Miniconda3/envs/ee
version:        3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/ProgramData/Miniconda3/envs/ee/Lib/site-packages/numpy
numpy_version:  1.18.1
ee:             C:\PROGRA~3\MINICO~1\envs\ee\lib\site-packages\ee\__init__.p

NOTE: Python version was forced by RETICULATE_PYTHON

All necessary python packages are installed OK.

Thank you.

**Comment by csaybar** [comment]
Hi, @GReimche thanks for report this issue.

Could you run in your terminal:
```
library(rgee)
ee$Initialize()
```
And show me the output.

**Comment by GReimche** [comment]
> library(rgee)
> ee$Initialize()
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  EEException: Please authorize access to your Earth Engine account by running

earthengine authenticate

in your command line, and then retry.

**Comment by csaybar** [comment]
Thanks for reporting this @GReimche!.
I found the problem.
```r
library(rgee)
ee$oauth$get_authorization_url()
```
The error is caused by a recent change in the Python API. I will correct this very soon.

**Comment by csaybar** [comment]
I made the changes, please reinstall rgee. Let me know if the error persists!

**Comment by GReimche** [comment]
Hi
I reinstalled rgee 0.3.1 and the API.
Results below

> ee$Initialize()

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  EEException: Please authorize access to your Earth Engine account by running

earthengine authenticate

in your command line, and then retry.

Detailed traceback: 
  File "C:\ProgramData\Miniconda3\envs\ee\lib\site-packages\ee\__init__.py", line 114, in Initialize
    credentials = data.get_persistent_credentials()
  File "C:\ProgramData\Miniconda3\envs\ee\lib\site-packages\ee\data.py", line 241, in get_persistent_credentials
    'Please authorize access to your Earth Engine account by '

**Comment by csaybar** [comment]
Hi @GReimche,

I had to add additional changes to `rgee v0.3.1` since `ee$oauth$request_token` (used in **ee_Initialize** ) also changed in the [`earthengine-api v0.1.124`](https://github.com/google/earthengine-api/commit/06b67a43bf535c606e2fc614835cedda838c1cc2).

Install once more time rgee, and run as follow:

```
library(rgee)
ee_Initialize()
```
I just tested it on windows. I think there will be no problem now. Please let me known.

**Comment by GReimche** [comment]
Hi Aybar!
Thank you very much for your attention. It is running fine now.

Obs! The api was updated a few hours to earthengine-api v0.1.216.

Best regards.

**Comment by csaybar** [comment]
No problem feel free to open as many issues as you want ^^. 
Happy coding :)
