### ISSUE TITLE
How to get ee$ImageCollection properties using rgee

### ISSUE THREAD

**Issue by GReimche** [csaybar/rgee#44]
Hi Cesar,
I'm trying to get the **'id**' and '**CLOUDY_PIXEL_PERCENTAGE**' from each of the images in a imageCollection using a function bellow but have no success with rgee.  
Would you be kind to show me how to handle this function with rgee?

getCloudScores = function(image){
  value = ee$Image(image)$get('CLOUDY_PIXEL_PERCENTAGE')
  return (print(value$getInfo()))
}

Cloudscores = imgcollection$map(getCloudScores)

**Comment by csaybar** [comment]
Hi @GReimche the idea to solve your problem is exactly the same that using the Python and Javascript API.  I would do something like this:

```r
library(rgee)
library(sf)

ee_Initialize()

nc <- st_read(system.file("shape/nc.shp", package = "sf")) %>%
  st_transform(4326) %>%
  sf_as_ee()

ee_s2 <- ee$ImageCollection("COPERNICUS/S2")$
  filterDate("2016-01-01", "2016-01-31")$
  filterBounds(nc)

Map$centerObject(nc, zoom = 6)
Map$addLayer(
  eeObject = ee_s2$mosaic(),
  visParams = list(
    bands = c("B4", "B3", "B2"),
    max = 6000,
    gamma = 1.6
  )
) +
Map$addLayer(nc)


ee_s2$aggregate_array("system:index")$getInfo()
ee_s2$aggregate_array("CLOUDY_PIXEL_PERCENTAGE")$getInfo()
```

**Comment by GReimche** [comment]
Thank you very much Cesar.
