### ISSUE TITLE
Error in py_get_attr_impl(x, name, silent) : OverflowError: Python int too large to convert to C long (ee_as_stars)

### ISSUE THREAD

**Issue by GReimche** [csaybar/rgee#47]
Hi Cesar,

  I'm trying to download an simple clipped image from gee using your function as bellow. But some seconds after it starts it shows the error bellow.
  The ee_image_to_drive function give's me the same error.
  Also, If I try the rgee exemple, I got the same erro. 

img_stars_01 <- ee_as_stars(
  image = image,
  region = geometry,
  geodesic = TRUE,
  via = "drive"
)

[1] "Polling for task (id: LZFOXKHACGLZTQIFAXJI63WU)."
[1] "Polling for task (id: LZFOXKHACGLZTQIFAXJI63WU)."
[1] "State: FAILED"
Error in py_get_attr_impl(x, name, silent) : 
  OverflowError: Python int too large to convert to C long

**Comment by csaybar** [comment]
Hi @GReimche It is a really strange error could you share us a reproducible example?

**Comment by GReimche** [comment]
I used the provided exemple in the "ee_as_stars" function in rgee. 
The "getInfo" via works, but "drive" via give the error bellow

> img_stars_02 <- ee_as_stars(
+   image = img,
+   region = geometry,
+   geodesic = FALSE,
+   via = "drive"
+ )
- region parameters
 WKT      : POLYGON ((515872.3 4938536, 531744.7 4938595, 531690.2 4949703, 515845.1 4949645, 515872.3 4938536)) 
 CRS      : 32612 
 geodesic : FALSE 
 evenOdd  : TRUE 

- download parameters (Google Drive)
 Image ID    : LANDSAT/LC08/C01/T1_SR/LC08_038029_20180810 
 Google user : user....
 Folder name : rgee_backup 
 Date        : 2020-04-07-00:52:44 
[1] "Polling for task (id: FNCTVHHISUMVPUTHO7UAIXOR)."
[1] "Polling for task (id: FNCTVHHISUMVPUTHO7UAIXOR)."
[1] "Polling for task (id: FNCTVHHISUMVPUTHO7UAIXOR)."
[1] "State: COMPLETED"
Error in py_get_attr_impl(x, name, silent) : 
  OverflowError: Python int too large to convert to C long

**Comment by csaybar** [comment]
Hi @GReimche, could show us your current earthengine-api and rgee version:
```
packageVersion('rgee')
rgee::ee_check()
```
It seems like a bug that we fix in version 0.3.5, I'm not able to reproduce the error in both windows and linux.

**Comment by GReimche** [comment]
> packageVersion('rgee')
[1] ‘0.3.8’
> rgee::ee_check()
(*)  Python version found: C:/ProgramData/Miniconda3/envs/ee/python.exe v3.8

(*)  Python Third-Party Libraries used in rgee: 

√ [Ok] Python Earth Engine API version 0.1.217
√ [Ok] oauth2client v 4.1.3
(*)  Credentials neccesaries for rgee: 

√ [Ok] Earth Engine Credentials found.
√ [Ok] Google Drive credentials found.
√ [Ok] Google Cloud Storage  credentials found.
>

**Comment by csaybar** [comment]
https://github.com/csaybar/rgee/blob/8e5c2e1f77d32befd84988363a4bd3f5988620c4/R/ee_stars.R#L429
After a successful running of `ee_image_to_drive` you should see the message above, do you see this?. Could you restart your R session and try it again?. It is a common problem in other Packages that use reticulate. Please notify us if the problem persists.

**Comment by GReimche** [comment]
Sad, but I have restarted R, and got the same error. But image are stored in Gdrive. When using via = "getInfo" I  receive image in Rstudio.

**Comment by csaybar** [comment]
`ee_as_stars` is not more than the functions `ee_image_to_drive()` and `ee_drive_to_local()` please run the follow script and tell me where the error occur:

```r
library(rgee)

# Initialize a specific Earth Engine account and load
# either Google Drive or Google Cloud Storage credentials
ee_reattach()
ee_Initialize(drive = TRUE)
img <- ee$Image("LANDSAT/LC08/C01/T1_SR/LC08_038029_20180810")$
  select(c("B4", "B3", "B2"))$
  divide(10000)
geometry <- ee$Geometry$Rectangle(c(-110.8, 44.6, -110.6, 44.7))
img_indrive <- ee_image_to_drive(
  image = img,
  description = 'myimage.tif',
  region = geometry
)
img_indrive$start()
ee_monitoring(img_indrive)
img_inlocal <- ee_drive_to_local(img_indrive)

```

**Comment by GReimche** [comment]
The error is still showing up but actually, the image is stored in gdrive, and is loaded by ee_drive_to_local function. 

library(rgee)
ee_Initialize(email = "username@gmail.com", drive = TRUE, gcs = FALSE)

img <- ee$Image("LANDSAT/LC08/C01/T1_SR/LC08_038029_20180810")$
  select(c("B4", "B3", "B2"))$
  divide(10000)
geometry <- ee$Geometry$Rectangle(c(-110.8, 44.6, -110.6, 44.7))
img_indrive <- ee_image_to_drive(
  image = img,
  description = 'myimage.tif',
  region = geometry
)
img_indrive$start()
ee_monitoring(img_indrive)

[1] "Polling for task (id: SQGSG6K7WRFNKBXIZE4FKBFO)."
[1] "Polling for task (id: SQGSG6K7WRFNKBXIZE4FKBFO)."
[1] "Polling for task (id: SQGSG6K7WRFNKBXIZE4FKBFO)."
[1] "State: COMPLETED"
Error in py_get_attr_impl(x, name, silent) : 
  OverflowError: Python int too large to convert to C long


img_inlocal <- ee_drive_to_local(img_indrive)

Auto-refreshing stale OAuth token.
File downloaded:
  * myimage.tif.tif
Saved locally as:
  * C:\Users\username\AppData\Local\Temp\RtmpcFcqgp/myimage.tif.tif

**Comment by csaybar** [comment]
Thanks a lot for reporting this :bug: . I was able to reproduce it. It will be fixed in the next version release!. Sorry for the inconvenience.
