### ISSUE TITLE
Returns an ImageCollection from given images.

### ISSUE THREAD

**Issue by giacfalk** [csaybar/rgee#48]
In GEE Javascript I type:

var imgcollection = ee.ImageCollection([img1, img2])

where img 1 and img2 are two standalone images.

How do I translate this in rgee?

**Comment by GReimche** [comment]
imgcollection <- ee$ImageCollection(list(img1, img2))

**Comment by csaybar** [comment]
As @GReimche say you could use either:

```r
ee_Initialize()

img_01 <- ee$Image(0)
img_02 <- ee$Image(1)

ic <- ee$ImageCollection(list(img_01, img_02))
ic <- ee$ImageCollection(c(img_01, img_02))
ee_help(ic)
```

**Comment by csaybar** [comment]
I am going to close this issue but feel free to open it again!
