### ISSUE TITLE
Batch exporting images with rgee? Possible?

### ISSUE THREAD

**Issue by philament** [csaybar/rgee#49]
A very useful package! Many thanks for your efforts. I have been testing it for a few days now and it mostly works great for me (with exception of `ee_as_stars()` which I have not been able to make work so far - by the way a function like `ee_as_raster()` would be very welcome for those of us who prefer the raster package over stars).

I have one question though: Is there an elegant way of exporting/downloading many (e.g. hundreds/thousands) of images or a simply an entire ImageCollection? I guess I could just somehow write a loop over `ee_image_to_drive()` and `ee_drive_to_local()` but it seems inelegant and keeping track of so many individual tasks is error-prone. Surely there must be a better way to accomplish this? If I can find a good way of doing this rgee will surely be my goto-package for EO processing as it finally makes working with GEE possible in R.

**Comment by giswqs** [comment]
@philament If you are familiar with Python, you can check out my [notebook example](https://github.com/giswqs/earthengine-py-notebooks/blob/master/AssetManagement/export_ee_data.ipynb) on how to do batch downloading of image and image collection. 

I just posted a [video tutorial](https://github.com/giswqs/geemap/tree/master/examples#exporting-earth-engine-image-and-imagecollection-as-geotiff-and-numpy-array) for downloadING images as GeoTIFF. Check it out.

**Comment by csaybar** [comment]
I think both suggestions are reasonable. In the version 3.10.0 of rgee I will add direct support to raster. We also plan to give support to ImageCollection download in rgee, but after solving some issues that currently we have with `ee_as_stars` and `ee_gcs_to_local`. When everything will ready I will write the code here!. By the way, did you mention that you get some issues using `ee_as_stars`?. We would very happy to fix these potential errors. So, feel free to open another issue to reporting us!

**Comment by philament** [comment]
@giswqs Thanks! Very nice. My Python knowledge is a bit limited but I think I will take your example as inspiration for coding something along these lines myself in R. I will check out your video tutorials, these look great!

@csaybar Sounds good. Support for raster will be very nice. And a "native" function such as `ee_imagecollection_to_drive()` or similar would be great if you can make it happen. Until that is the case I will just work with loops as in the example provided by @giswqs . As for the issues with `ee_as_stars` I had, I think it was more user error than bugs, but if I can reproduce the issues I had I will post them here. Again, thanks for your efforts - keep up the good work!

**Comment by csaybar** [comment]
Hi, @philament I added a new function `ee_imagecollection_to_local` in rgee 0.3.10. Based on the example provides by @giswqs, the code in R will be:
```r
library(rgee)
library(raster)

# Initialize a specific Earth Engine account and load
# either Google Drive or Google Cloud Storage credentials
ee_reattach()
ee_Initialize(
  email = "data.colec.fbf@gmail.com",
  drive = TRUE,
  gcs = TRUE
)

# USDA example
loc <- ee$Geometry$Point(-99.2222, 46.7816)
collection <- ee$ImageCollection('USDA/NAIP/DOQQ')$
  filterBounds(loc)$
  filterDate('2008-01-01', '2020-01-01')$
  filter(ee$Filter$listContains("system:band_names", "N"))

# From ImageCollection to local directory
ee_crs <- collection$first()$projection()$getInfo()$crs
geometry <- collection$first()$geometry(proj = ee_crs)$bounds()
tmp <- tempdir()

## Using getInfo
ic_getinfo_files <- ee_imagecollection_to_local(
  ic = collection,
  region = geometry,
  scale = 100,
  dsn = tmp,
  via = "getInfo",
  quiet = TRUE
)

## Using drive
ic_drive_files <- ee_imagecollection_to_local(
  ic = collection,
  region = geometry,
  scale = 100,
  dsn = file.path(tmp, "drive_"),
  via = "drive"
)

# Testing results
raster(ic_getinfo_files[1]) - raster(ic_getinfo_files[1])

```
I had to do several changes in rgee 0.3.10. Please see [rgee 0.3.10](https://github.com/csaybar/rgee/blob/master/NEWS.md)

**Comment by philament** [comment]
Well done! This looks great! I got this example running without issues. For my own test with S5P data I am still struggling a bit with setting the crs of the geometry right, but I will figure it out eventually. 

Should the last line of your example be 
`raster(ic_getinfo_files[1]) - raster(ic_drive_files[1])` ?
Otherwise I don't get the point.

I also like the new behaviour of ee_print() in 0.3.10. Very nice.

**Comment by csaybar** [comment]
Thanks for contributing to `rgee`. The version 0.4.0 was released where ee_imagecollection_to_local is continuously tested. I going to close this issue but feel free to open it again.
