### ISSUE TITLE
ee_map do not display ee$Image

### ISSUE THREAD

**Issue by csaybar** [csaybar/rgee#5]
createTimeBand <-function(img) {
  year <- ee$Date(img$get('system:time_start'))$get('year')$subtract(1991L)
  ee$Image(year)$byte()$addBands(img)
}

collection = ee$
  ImageCollection('NOAA/DMSP-OLS/NIGHTTIME_LIGHTS')$
  select('stable_lights')$
  map(createTimeBand)

col_reduce = collection$reduce(ee$Reducer$linearFit())
col_reduce$getInfo
ee_map(eeobject = col_reduce,
       vizparams = list(min=0, max= c(0.18, 20, -0.18),
       bands=c('scale', 'offset', 'scale')),
       objname = 'stable lights trend')

**Comment by ryali93** [comment]
token from ee_map.py:
getMapId()["tile_fetcher"].url_format

create_beauty_basemap:
addWMSTiles(baseUrl = tile, group = objname, layers = "0") %>%
addTiles(urlTemplate = tile, group = objname) %>%
