### ISSUE TITLE
"Rd warning" during installation of rgee package

### ISSUE THREAD

**Issue by safalabolo** [csaybar/rgee#50]
Hi csaybar,
During the installation of rgee I have warnings that are reflected in the next steps.
Following the console of Rstudio, I hope they can be solved. 
Thanks for the reply.

> remotes::install_github("csaybar/rgee",force=TRUE)
Downloading GitHub repo csaybar/rgee@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

 1: All                              
 2: CRAN packages only               
 3: None                             
 4: sf        (0.9-0 -> 0.9-1) [CRAN]
 5: isoband   (0.2.0 -> 0.2.1) [CRAN]
 6: tibble    (2.1.3 -> 3.0.0) [CRAN]
 7: callr     (3.4.2 -> 3.4.3) [CRAN]
 8: backports (1.1.5 -> 1.1.6) [CRAN]
 9: gdtools   (0.2.1 -> 0.2.2) [CRAN]
10: lwgeom    (0.2-1 -> 0.2-3) [CRAN]
11: leafem    (0.0.1 -> 0.1.1) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
1
sf        (0.9-0 -> 0.9-1) [CRAN]
isoband   (0.2.0 -> 0.2.1) [CRAN]
tibble    (2.1.3 -> 3.0.0) [CRAN]
callr     (3.4.2 -> 3.4.3) [CRAN]
backports (1.1.5 -> 1.1.6) [CRAN]
gdtools   (0.2.1 -> 0.2.2) [CRAN]
lwgeom    (0.2-1 -> 0.2-3) [CRAN]
leafem    (0.0.1 -> 0.1.1) [CRAN]
Installing 8 packages: sf, isoband, tibble, callr, backports, gdtools, lwgeom, leafem
Installing packages into ‘C:/Users/safalabolo/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)

  There are binary versions available but the source versions are later:
        binary source needs_compilation
sf       0.9-0  0.9-1              TRUE
isoband  0.2.0  0.2.1              TRUE
lwgeom   0.2-1  0.2-3              TRUE

  Binaries will be installed
provo con l'URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/sf_0.9-0.zip'
Content type 'application/zip' length 39675549 bytes (37.8 MB)
downloaded 37.8 MB

provo con l'URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/isoband_0.2.0.zip'
Content type 'application/zip' length 2902648 bytes (2.8 MB)
downloaded 2.8 MB

provo con l'URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/tibble_3.0.0.zip'
Content type 'application/zip' length 407169 bytes (397 KB)
downloaded 397 KB

provo con l'URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/callr_3.4.3.zip'
Content type 'application/zip' length 390066 bytes (380 KB)
downloaded 380 KB

provo con l'URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/backports_1.1.6.zip'
Content type 'application/zip' length 77492 bytes (75 KB)
downloaded 75 KB

provo con l'URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/gdtools_0.2.2.zip'
Content type 'application/zip' length 3534664 bytes (3.4 MB)
downloaded 3.4 MB

provo con l'URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/lwgeom_0.2-1.zip'
Content type 'application/zip' length 5358478 bytes (5.1 MB)
downloaded 5.1 MB

provo con l'URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/leafem_0.1.1.zip'
Content type 'application/zip' length 2965827 bytes (2.8 MB)
downloaded 2.8 MB

package ‘sf’ successfully unpacked and MD5 sums checked
package ‘isoband’ successfully unpacked and MD5 sums checked
package ‘tibble’ successfully unpacked and MD5 sums checked
package ‘callr’ successfully unpacked and MD5 sums checked
package ‘backports’ successfully unpacked and MD5 sums checked
package ‘gdtools’ successfully unpacked and MD5 sums checked
package ‘lwgeom’ successfully unpacked and MD5 sums checked
package ‘leafem’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\safalabolo\AppData\Local\Temp\RtmpmQHHIi\downloaded_packages
√  checking for file 'C:\Users\safalabolo\AppData\Local\Temp\RtmpmQHHIi\remotes3bd4600f2784\csaybar-rgee-31ed555/DESCRIPTION' (868ms)
-  preparing 'rgee': (1s)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (763ms)
-  checking for empty or unneeded directories
-  building 'rgee_0.3.9.tar.gz'
   
Installing package into ‘C:/Users/safalabolo/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'rgee' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'rgee'
    finding HTML links ... fatto
    Map                                     html  
Rd warning: C:/Users/safalabolo/AppData/Local/Temp/Rtmp2fwh5E/R.INSTALL1e9c72f44fa9/rgee/man/Map.Rd:54: file link 'mapview' in package 'mapview' does not exist and so has been treated as a topic
Rd warning: C:/Users/safalabolo/AppData/Local/Temp/Rtmp2fwh5E/R.INSTALL1e9c72f44fa9/rgee/man/Map.Rd:60: file link 'mapview' in package 'mapview' does not exist and so has been treated as a topic
    create_shp_zip                          html  
    ee_Initialize                           html  
    ee_as_sf                                html  
    ee_as_stars                             html  
    ee_as_thumbnail                         html  
    ee_check-tools                          html  
    ee_clean_container                      html  
    ee_clean_pyenv                          html  
    ee_create_pyenv                         html  
    ee_discover_pyenvs                      html  
Rd warning: C:/Users/safalabolo/AppData/Local/Temp/Rtmp2fwh5E/R.INSTALL1e9c72f44fa9/rgee/man/ee_discover_pyenvs.Rd:14: file link 'conda_list' in package 'reticulate' does not exist and so has been treated as a topic
Rd warning: C:/Users/safalabolo/AppData/Local/Temp/Rtmp2fwh5E/R.INSTALL1e9c72f44fa9/rgee/man/ee_discover_pyenvs.Rd:15: file link 'virtualenv_list' in package 'reticulate' does not exist and so has been treated as a topic
    ee_drive_to_local                       html  
    ee_extract                              html  
    ee_gcs_to_asset_image                   html  
    ee_gcs_to_asset_table                   html  
    ee_gcs_to_local                         html  
    ee_get_assethome                        html  
    ee_get_earthengine_path                 html  
    ee_get_ic_date                          html  
    ee_get_img_date                         html  
    ee_help                                 html  
    ee_image_info                           html  
    ee_image_to_asset                       html  
    ee_image_to_drive                       html  
    ee_image_to_gcs                         html  
    ee_install_python_packages              html  
Rd warning: C:/Users/safalabolo/AppData/Local/Temp/Rtmp2fwh5E/R.INSTALL1e9c72f44fa9/rgee/man/ee_install_python_packages.Rd:46: file link 'conda_install' in package 'reticulate' does not exist and so has been treated as a topic
Rd warning: C:/Users/safalabolo/AppData/Local/Temp/Rtmp2fwh5E/R.INSTALL1e9c72f44fa9/rgee/man/ee_install_python_packages.Rd:47: file link 'virtualenv_install' in package 'reticulate' does not exist and so has been treated as a topic
    ee_local_to_gcs                         html  
    ee_manage-tools                         html  
Rd warning: C:/Users/safalabolo/AppData/Local/Temp/Rtmp2fwh5E/R.INSTALL1e9c72f44fa9/rgee/man/ee_manage-tools.Rd:81: file link 'ee_manage_delete_properties' in package 'rgee' does not exist and so has been treated as a topic
    ee_monitoring                           html  
    ee_print                                html  
    ee_py_to_r                              html  
    ee_pyfunc                               html  
    ee_reattach                             html  
    ee_remove_credentials                   html  
    ee_remove_project_chr                   html  
    ee_search-tools                         html  
    ee_set_pyenv                            html  
    ee_table_to_asset                       html  
    ee_table_to_drive                       html  
    ee_table_to_gcs                         html  
    ee_user_info                            html  
    ee_users                                html  
    ee_version                              html  
    eedate_to_rdate                         html  
    pipe                                    html  
    plus-mapview-mapview-method             html  
    rdate_to_eedate                         html  
    rgee-package                            html  
    sf_as_ee                                html  
    stars_as_ee                             html  
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (rgee)

**Comment by csaybar** [comment]
Hi @safalabolo  thanks for reporting this!

We will work to solve these issues in the next release. Keep tuned!

**Comment by csaybar** [comment]
Thanks, it will be solved in rgee 0.4.0. Please, open this issue again if the problem persists.
