### ISSUE TITLE
Error: Python module ee was not found.

### ISSUE THREAD

**Issue by mariofajardo** [csaybar/rgee#51]
Hi

Nice effort in putting this package together.

I first installed the package in a windows 10 machine with Anaconda 3 installation and working multiple conda environments. 

In order to keep things tidy I follow the instructions about creating a different environment.I was asked to install miniconda, which I denied...since I have the full installation of conda, so didn't want to make things confusing.

I tried to install packages but It throw an error... re opened R and tried to initialize again (first time went smooth with my default python env) and now I'm getting this error when ee.Initialize().

```
Error: Python module ee was not found.

Detected Python configuration:

python:         C:/Users/Mario/Documents/.conda/envs/RGee1/python.exe
libpython:      C:/Users/Mario/Documents/.conda/envs/RGee1/python38.dll
pythonhome:     C:/Users/Mario/Documents/.conda/envs/RGee1
version:        3.8.2 (default, Mar 25 2020, 08:56:29) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:           [NOT FOUND]
ee:             [NOT FOUND]

NOTE: Python version was forced by RETICULATE_PYTHON
```

PS. The whole thing stopped working now..on every single environment. I guess I'm going back to python. 

Thanks anyway!

Mario

**Comment by csaybar** [comment]
Hi @mariofajardo we will happy to help you to solve installation problems (we still working to find the best installation interface). Please attached us more information about your system using #22 


PS: Do not forget to look at the  [Python Installation guide](https://developers.google.com/earth-engine/python_install) and [Requirements](https://github.com/csaybar/rgee#requirements).

**Comment by csaybar** [comment]
I'm going to close this issue due to the lack of information about the error.
