### ISSUE TITLE
ee_image_as_raster 

### ISSUE THREAD

**Issue by GReimche** [csaybar/rgee#53]
Hi Cesar,
I'm trying to export an image with some veg index bands and I'm getting error with the one using the expression **normalizedDifference**. like bellow. Other like EVI and others are exported fine.

I use the `imageexport= image$addBands(ndvi)$addBands(ndwi )` before exporting with the 
`ee_image_as_raster` function.

`ndvi <- image$normalizedDifference(c("B8", "B4"))$rename("NDVI")`
`ndwi <- image$normalizedDifference(c("B3", "B8"))$rename("NDWI")`

`evi <- image$expression(
  expression = "2.5 * (float(nir - red) / (nir + 6 * red - 7.5 * blue + 1))",
  opt_map = list(
    nir = image$select("B8"),
    red = image$select("B4"),
    blue = image$select("B2")))$rename('EVI')`  

**Error report**
`[1] "Polling for task (id: EFCK53BBQER44IYTRNWRJ3GZ)."
[1] "Polling for task (id: EFCK53BBQER44IYTRNWRJ3GZ)."
[1] "Polling for task (id: EFCK53BBQER44IYTRNWRJ3GZ)."
[1] "State: FAILED"
Error in py_get_attr_impl(x, name, silent) : 
  OverflowError: Python int too large to convert to C long
Moving image from Google Drive to Local ... Please wait  
Error in basename(task$status()$destination_uris) :
character vector expected as an argument `

` ee_check()
(*)  Python version found: C:/ProgramData/Miniconda3/envs/ee/python.exe v3.8

(*)  Python Third-Party Libraries used in rgee: 

√ [Ok] Python Earth Engine API version 0.1.218
√ [Ok] pyasn1 v 0.4.8
√ [Ok] urllib3 v 1.25.9
√ [Ok] oauth2client v 4.1.3
√ [Ok] numpy v 1.18.1

(*)  Credentials neccesaries for rgee: 

√ [Ok] Earth Engine Credentials found.
√ [Ok] Google Drive credentials found.
√ [Ok] Google Cloud Storage  credentials found.`

**Comment by csaybar** [comment]
hi, @GReimche Thanks for reporting this. This error happens because Earth Engine Failed to move your image to Google Drive. I will add more message diagnostic for this error in the next release. Could you say me your rgee version and attached here a complete reproducible example?. Thanks a lot for your help!

**Comment by GReimche** [comment]
rgee version is 0.3.14

**Comment by csaybar** [comment]
Could you specify what is image variable exactly?

**Comment by GReimche** [comment]
`imagem1 and imagem2` are two `ee$Image.`

`imagecol<- ee$ImageCollection(c(imagem1, imagem2))
imagemed= imagecol$median()
image= imagemed$clip(geometry_buff)`

**Comment by csaybar** [comment]
I do not get the error you mention to calculate the EVI. Your error possibly is in your expression.

```r
library(rgee)
library(raster)

# Initialize a specific Earth Engine account and load
# either Google Drive or Google Cloud Storage credentials
ee_reattach()
ee_Initialize(
  email = "data.colec.fbf@gmail.com",
  drive = TRUE
)

# Load a Landsat 8 image.
image = ee$Image('LANDSAT/LC08/C01/T1_TOA/LC08_044034_20140318')

# Compute the EVI using an expression.
evi = image$expression(
  expression = '2.5 * ((NIR - RED) / (NIR + 6 * RED - 7.5 * BLUE + 1))',
  opt_map =  list(
    'NIR' = image$select('B5'),
    'RED' = image$select('B4'),
    'BLUE' = image$select('B2')
  )
)

Map$centerObject(image, 9)
Map$addLayer(evi, list(min = -1, max = 1, palette = c('FF0000', '00FF00')))

img_rs <- ee_image_as_raster(
  image = evi, 
  scale = 1000,
  region = image$geometry(),
  via = "drive"
)
# ee_manage_cancel_all_running_task() [cancel your EE tasks!]
plot(img_rs)
```

**Comment by GReimche** [comment]
This just runs fine.
 It fails just when using the **normalizedDifference** in the function, while computing ndvi, ndwi, mndwi and others.
