### ISSUE TITLE
Error in ee_check_python(quiet = TRUE) :    rgee just run under Python 3.5 >=

### ISSUE THREAD

**Issue by oleksandrkarasov** [csaybar/rgee#56]
Dear Cesar,
Thank you for support with the previous installation issue. When installing rgee on the working computer I face another problem: R prefers python for ArcGIS instead of freshly installed Miniconda, which is intended to be detectable as a main Python installation by default. Could you, please, help in this regard?

Please, find the code as follows:
`> ee_Initialize()
Error: Python module ee was not found.

Detected Python configuration:

python:         C:/Python27/ArcGISx6410.4/python.exe
libpython:      python27.dll
pythonhome:     C:/Python27/ArcGISx6410.4
version:        2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Python27/ArcGISx6410.4/Lib/site-packages/numpy
numpy_version:  1.9.2
ee:             [NOT FOUND]

python versions found: 
 G:/MySoft/Miniconda/python.exe
 C:/Python27/ArcGISx6410.4/python.exe
 C:/Python32/python.exe
 C:/Anaconda3/python.exe

In addition: Warning messages:
1: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpYdZOtU\file2268598b30d5'
2: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpYdZOtU\file2268b0e5a'
> ee_create_pyenv(python_env = "ee")
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: G:\MySoft\MINICO~1\envs\ee

  added / updated specs:
    - python

The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/win-64::ca-certificates-2020.1.1-0
  certifi            pkgs/main/win-64::certifi-2020.4.5.1-py38_0
  openssl            pkgs/main/win-64::openssl-1.1.1g-he774522_0
  pip                pkgs/main/win-64::pip-20.0.2-py38_1
  python             pkgs/main/win-64::python-3.8.2-h5fd99cc_11
  setuptools         pkgs/main/win-64::setuptools-46.1.3-py38_0
  sqlite             pkgs/main/win-64::sqlite-3.31.1-h2a8f88b_1
  vc                 pkgs/main/win-64::vc-14.1-h0510ff6_4
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.16.27012-hf0eaf9b_1
  wheel              pkgs/main/win-64::wheel-0.34.2-py38_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py38_0
  zlib               pkgs/main/win-64::zlib-1.2.11-h62dcd97_4

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

==> WARNING: A newer version of conda exists. <==
  current version: 4.8.2
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda

#
# To activate this environment, use
#
#     $ conda activate ee
#
# To deactivate an active environment, use
#
#     $ conda deactivate

> ee_check_python()
(*)  Python version found: C:/Python27/ArcGISx6410.4/python.exe v2.7
Error in ee_check_python() : rgee just run under Python 3.5 >=
In addition: Warning messages:
1: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpYdZOtU\file22682cb37bf'
2: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpYdZOtU\file226825a5870'
3: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpYdZOtU\file2268193e466a'
4: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpYdZOtU\file22686015663'
> ee_discover_pyenvs()
[1] "G:\\MySoft\\Miniconda\\python.exe"          
[2] "G:\\MySoft\\Miniconda\\envs\\ee\\python.exe"
> ee_set_pyenv(
+ python_path = 'G:\\MySoft\\Miniconda\\envs\\ee\\python.exe',
+ python_env = 'ee',
+ install = TRUE
+ )
rgee needs to restart R session to see changes.
Do you want to continues? 

1: yes
2: no

Selection: 2
> ee_install_python_packages()
Error in ee_check_python(quiet = TRUE) : 
  rgee just run under Python 3.5 >=
In addition: Warning messages:
1: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpYdZOtU\file22682bec6a33'
2: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpYdZOtU\file22681f5b586'
> 

#Checkist
> earthengine -h
Error: object 'earthengine' not found
> library(rgee)
> ee_path <- path.expand("~/.config/earthengine/credentials")
> file.exists(ee_path)
[1] FALSE
> library(rgee)
> 
> # Initialize the Earth Engine module.
> ee_Initialize()
Error: Python module ee was not found.

Detected Python configuration:

python:         C:/Python27/ArcGISx6410.4/python.exe
libpython:      python27.dll
pythonhome:     C:/Python27/ArcGISx6410.4
version:        2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Python27/ArcGISx6410.4/Lib/site-packages/numpy
numpy_version:  1.9.2
ee:             [NOT FOUND]

python versions found: 
 G:/MySoft/Miniconda/python.exe
 C:/Python27/ArcGISx6410.4/python.exe
 C:/Python32/python.exe
 C:/Anaconda3/python.exe

> 
> # Print metadata for a DEM dataset.
> print(ee$Image('USGS/SRTMGL1_003')$getInfo())
Error: Python module ee was not found.

Detected Python configuration:

python:         C:/Python27/ArcGISx6410.4/python.exe
libpython:      python27.dll
pythonhome:     C:/Python27/ArcGISx6410.4
version:        2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Python27/ArcGISx6410.4/Lib/site-packages/numpy
numpy_version:  1.9.2
ee:             [NOT FOUND]

python versions found: 
 G:/MySoft/Miniconda/python.exe
 C:/Python27/ArcGISx6410.4/python.exe
 C:/Python32/python.exe
 C:/Anaconda3/python.exe

> library(reticulate)
> py_config()
python:         C:/Python27/ArcGISx6410.4/python.exe
libpython:      python27.dll
pythonhome:     C:/Python27/ArcGISx6410.4
version:        2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Python27/ArcGISx6410.4/Lib/site-packages/numpy
numpy_version:  1.9.2
ee:             [NOT FOUND]

python versions found: 
 G:/MySoft/Miniconda/python.exe
 C:/Python27/ArcGISx6410.4/python.exe
 C:/Python32/python.exe
 C:/Anaconda3/python.exe
> 
`

**Comment by csaybar** [comment]
Hi @oleksandrkarasov thanks for reporting this. It is a scenario that we do not contemplate. You can solve it setting the PythonPath before creating a virtualenv.

```
ee_Initialize()
ee_set_pyenv(python_path = "/home/CHANGE_BY_YOUR_USER/.virtualenvs/ee/bin/python")
ee_create_pyenv(python_env = "ee")
ee_discover_pyenvs()
ee_set_pyenv(python_path = "/home/CHANGE_BY_YOUR_USER/.virtualenvs/ee/bin/python")
ee_install_python_packages()
ee_Initialize()
```

**Comment by oleksandrkarasov** [comment]
Dear @csaybar ,
thanks for explanation! The code until "ee_install_python_packages()" worked well; however, at this stage I see the problem, which might be related to Windows specifics:
`> ee_install_python_packages()
Error: Installing Python packages into a virtualenv is not supported on Windows`

Could you, please, provide solution for Windows?

**Comment by csaybar** [comment]
Sorry, It could be on this form:

```
ee_Initialize()
ee_set_pyenv(python_path = "PUT HERE YOUR PYTHON PATH")
ee_create_pyenv(python_env = "ee")
ee_discover_pyenvs()
ee_set_pyenv(python_path = "PUT HERE THE  PATH OF THE PYTHON VIRTUAL ENV"")
ee_install_python_packages()
ee_Initialize()
```

We would have an easier way to install rgee in the next release. Please say me if this solves your problem.

**Comment by oleksandrkarasov** [comment]
Dear @csaybar , thank you, but still the problem exists: R considers ArcGIS python by default after the R restart even in case I have set python environment and installed packages specifically for relevant Python:
`> ee_Initialize()
Error: Python module ee was not found.

Detected Python configuration:

python:         C:/Python27/ArcGISx6410.4/python.exe
libpython:      python27.dll
pythonhome:     C:/Python27/ArcGISx6410.4
version:        2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Python27/ArcGISx6410.4/Lib/site-packages/numpy
numpy_version:  1.9.2
ee:             [NOT FOUND]

python versions found: 
 G:/MySoft/Miniconda/python.exe
 C:/Python27/ArcGISx6410.4/python.exe
 C:/Python32/python.exe
 C:/Anaconda3/python.exe

In addition: Warning messages:
1: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpKKWLFr\file7443855236'
2: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpKKWLFr\file74445a557c6'
> ee_set_pyenv(python_path = "G:/MySoft/Miniconda/python.exe",install = TRUE)
python_env is NULL, RETICULATE_PYTHON_ENV will not be created.
rgee needs to restart R session to see changes.
Do you want to continues? 

1: yes
2: no

Selection: ee_check_python()
Enter an item from the menu, or 0 to exit
Selection: 2
> ee_check_python()
(*)  Python version found: G:/MySoft/Miniconda/python.exe v3.7
> ee_create_pyenv(python_env = "ee")
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: G:\MySoft\MINICO~1\envs\ee

  added / updated specs:
    - python


The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/win-64::ca-certificates-2020.1.1-0
  certifi            pkgs/main/win-64::certifi-2020.4.5.1-py38_0
  openssl            pkgs/main/win-64::openssl-1.1.1g-he774522_0
  pip                pkgs/main/win-64::pip-20.0.2-py38_1
  python             pkgs/main/win-64::python-3.8.2-h5fd99cc_11
  setuptools         pkgs/main/win-64::setuptools-46.1.3-py38_0
  sqlite             pkgs/main/win-64::sqlite-3.31.1-h2a8f88b_1
  vc                 pkgs/main/win-64::vc-14.1-h0510ff6_4
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.16.27012-hf0eaf9b_1
  wheel              pkgs/main/win-64::wheel-0.34.2-py38_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py38_0
  zlib               pkgs/main/win-64::zlib-1.2.11-h62dcd97_4


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.2
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda


#
# To activate this environment, use
#
#     $ conda activate ee
#
# To deactivate an active environment, use
#
#     $ conda deactivate

> ee_discover_pyenvs() 
[1] "G:\\MySoft\\Miniconda\\python.exe"          
[2] "G:\\MySoft\\Miniconda\\envs\\ee\\python.exe"
> ee_set_pyenv(
+ python_path = 'G:\\MySoft\\Miniconda\\envs\\ee\\python.exe',
+ python_env = 'ee',
+ install = TRUE
+ )
rgee needs to restart R session to see changes.
Do you want to continues? 

1: yes
2: no

Selection: 
Enter an item from the menu, or 0 to exit
Selection: 2
> ee_check_python()
(*)  Python version found: G:/MySoft/Miniconda/envs/ee/python.exe v3.8
> ee_install_python_packages()
Error: could not find a Python environment for C:/Python27/ArcGISx6410.4/python.exe
> ee_install_python_packages(envname="G:\\MySoft\\Miniconda\\envs\\ee")
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: G:\MySoft\Miniconda\envs\ee

  added / updated specs:
    - python=3.7


The following packages will be DOWNGRADED:

certifi                                 2020.4.5.1-py38_0 --> 2020.4.5.1-py37_0
  pip                                         20.0.2-py38_1 --> 20.0.2-py37_1
  python                                  3.8.2-h5fd99cc_11 --> 3.7.7-h60c2a47_2
  setuptools                                  46.1.3-py38_0 --> 46.1.3-py37_0
  wheel                                       0.34.2-py38_0 --> 0.34.2-py37_0
  wincertstore                                   0.2-py38_0 --> 0.2-py37_0


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.2
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda


Processing c:\users\burdun\appdata\local\pip\cache\wheels\15\77\14\f3f69405694037e040add146a4fd8c481cbac44effbfff26be\earthengine_api-0.1.219-py3-none-any.whl
Collecting oauth2client
  Using cached oauth2client-4.1.3-py2.py3-none-any.whl (98 kB)
Collecting six
  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
Processing c:\users\burdun\appdata\local\pip\cache\wheels\b7\3d\b4\033d07bc6a387ce6e16807fe14d4b780d84c78e54dc73a3568\httplib2shim-0.0.3-py2.py3-none-any.whl
Collecting google-cloud-storage
  Using cached google_cloud_storage-1.28.0-py2.py3-none-any.whl (80 kB)
Collecting google-auth-httplib2>=0.0.3
  Using cached google_auth_httplib2-0.0.3-py2.py3-none-any.whl (6.3 kB)
Collecting httplib2<1dev,>=0.9.2
  Using cached httplib2-0.17.3-py3-none-any.whl (95 kB)
Collecting google-api-python-client
  Using cached google_api_python_client-1.8.2-py3-none-any.whl (58 kB)
Processing c:\users\burdun\appdata\local\pip\cache\wheels\56\b0\fe\4410d17b32f1f0c3cf54cdfb2bc04d7b4b8f4ae377e2229ba0\future-0.18.2-py3-none-any.whl
Collecting google-auth>=1.4.1
  Using cached google_auth-1.14.1-py2.py3-none-any.whl (89 kB)
Collecting rsa>=3.1.4
  Using cached rsa-4.0-py2.py3-none-any.whl (38 kB)
Collecting pyasn1-modules>=0.0.5
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting pyasn1>=0.1.7
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting urllib3
  Using cached urllib3-1.25.9-py2.py3-none-any.whl (126 kB)
Requirement already satisfied, skipping upgrade: certifi in g:\mysoft\minico~1\envs\ee\lib\site-packages (from httplib2shim->earthengine-api==0.1.219) (2020.4.5.1)
Collecting google-resumable-media<0.6dev,>=0.5.0
  Using cached google_resumable_media-0.5.0-py2.py3-none-any.whl (38 kB)
Collecting google-cloud-core<2.0dev,>=1.2.0
  Using cached google_cloud_core-1.3.0-py2.py3-none-any.whl (26 kB)
Collecting uritemplate<4dev,>=3.0.0
  Using cached uritemplate-3.0.1-py2.py3-none-any.whl (15 kB)
Collecting google-api-core<2dev,>=1.13.0
  Using cached google_api_core-1.17.0-py2.py3-none-any.whl (70 kB)
Collecting cachetools<5.0,>=2.0.0
  Using cached cachetools-4.1.0-py3-none-any.whl (10 kB)
Requirement already satisfied, skipping upgrade: setuptools>=40.3.0 in g:\mysoft\minico~1\envs\ee\lib\site-packages (from google-auth>=1.4.1->earthengine-api==0.1.219) (46.1.3.post20200330)
Collecting requests<3.0.0dev,>=2.18.0
  Using cached requests-2.23.0-py2.py3-none-any.whl (58 kB)
Collecting protobuf>=3.4.0
  Using cached protobuf-3.11.3-cp37-cp37m-win_amd64.whl (1.0 MB)
Collecting pytz
  Using cached pytz-2020.1-py2.py3-none-any.whl (510 kB)
Processing c:\users\burdun\appdata\local\pip\cache\wheels\4c\a1\71\5e427276ceeff277fd76878d1b19fbf4587a2845015d86864b\googleapis_common_protos-1.51.0-py3-none-any.whl
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.9-py2.py3-none-any.whl (58 kB)
Installing collected packages: six, httplib2, urllib3, httplib2shim, pyasn1, pyasn1-modules, rsa, cachetools, google-auth, google-resumable-media, chardet, idna, requests, protobuf, pytz, googleapis-common-protos, google-api-core, google-cloud-core, google-cloud-storage, google-auth-httplib2, uritemplate, google-api-python-client, future, earthengine-api, oauth2client

WARNING: The scripts pyrsa-decrypt.exe, pyrsa-encrypt.exe, pyrsa-keygen.exe, pyrsa-priv2pub.exe, pyrsa-sign.exe and pyrsa-verify.exe are installed in 'G:\MySoft\MINICO~1\envs\ee\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script chardetect.exe is installed in 'G:\MySoft\MINICO~1\envs\ee\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts futurize.exe and pasteurize.exe are installed in 'G:\MySoft\MINICO~1\envs\ee\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script earthengine.exe is installed in 'G:\MySoft\MINICO~1\envs\ee\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed cachetools-4.1.0 chardet-3.0.4 earthengine-api-0.1.219 future-0.18.2 google-api-core-1.17.0 google-api-python-client-1.8.2 google-auth-1.14.1 google-auth-httplib2-0.0.3 google-cloud-core-1.3.0 google-cloud-storage-1.28.0 google-resumable-media-0.5.0 googleapis-common-protos-1.51.0 httplib2-0.17.3 httplib2shim-0.0.3 idna-2.9 oauth2client-4.1.3 protobuf-3.11.3 pyasn1-0.4.8 pyasn1-modules-0.2.8 pytz-2020.1 requests-2.23.0 rsa-4.0 six-1.14.0 uritemplate-3.0.1 urllib3-1.25.9

Installation complete.

rgee needs to restart R session to see changes.
Do you want to continues? 

1: yes
2: no

Selection: 
#####Restarted
> library(rgee)
> ee_Initialize()
Error: Python module ee was not found.

Detected Python configuration:

python:         C:/Python27/ArcGISx6410.4/python.exe
libpython:      python27.dll
pythonhome:     C:/Python27/ArcGISx6410.4
version:        2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Python27/ArcGISx6410.4/Lib/site-packages/numpy
numpy_version:  1.9.2
ee:             [NOT FOUND]

python versions found: 
 G:/MySoft/Miniconda/envs/ee/python.exe
 G:/MySoft/Miniconda/python.exe
 C:/Python27/ArcGISx6410.4/python.exe
 C:/Python32/python.exe
 C:/Anaconda3/python.exe

In addition: Warning messages:
1: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\Rtmpi2lzvm\file1b9025035d28'
2: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\Rtmpi2lzvm\file1b906e846cf'
>`

**Comment by csaybar** [comment]
Hi @oleksandrkarasov please upgrade rgee to 0.4.1 version and run as is indicated here:

https://csaybar.github.io/rgee/articles/faq.html

**Comment by oleksandrkarasov** [comment]
Dear @csaybar 
Still after each restart R considers ArcGIS Python first, despite the manually indicated path to the correct one:

` library(rgee)
> Sys.getenv("R_USER")
[1] "G:/R_TMP"
> ee_check_python()
(*)  Python version found: C:/Python27/ArcGISx6410.4/python.exe v2.7
Error in ee_check_python() : rgee just run under Python 3.5 >=
In addition: Warning messages:
1: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpuqbmgK\file7b879704b4a'
2: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpuqbmgK\file7b8310177be'
3: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpuqbmgK\file7b831b63d62'
4: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpuqbmgK\file7b8584327f'
5: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpuqbmgK\file7b8772b4a4b'
6: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpuqbmgK\file7b8277610d3'
> ee_discover_pyenvs() 
[1] "C:\\Anaconda3\\envs\\ee\\python.exe"        
[2] "G:\\MySoft\\Miniconda\\python.exe"          
[3] "G:\\MySoft\\Miniconda\\envs\\ee\\python.exe"
>   myPythonPath <- "G:\\MySoft\\Miniconda\\python.exe"
>   ee_set_pyenv(myPythonPath)
python_env is NULL, RETICULATE_PYTHON_ENV will not be created.
To install this Python environment for use in future sessions, run this function with `install = TRUE`.
>   ee_set_pyenv(myPythonPath, install = TRUE)
python_env is NULL, RETICULATE_PYTHON_ENV will not be created.
rgee needs to restart R session to see changes.
Do you want to continues? 

1: yes
2: no

Selection: 
1
#RESTART
 library(rgee)
> Sys.getenv("R_USER")
[1] "G:/R_TMP"
> ee_check_python()
(*)  Python version found: C:/Python27/ArcGISx6410.4/python.exe v2.7
Error in ee_check_python() : rgee just run under Python 3.5 >=
In addition: Warning messages:
1: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpWKQvby\file2b38e6b3e9f'
2: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpWKQvby\file2b3837b0419e'
3: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpWKQvby\file2b3859a029'
4: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpWKQvby\file2b38740c5bca'
5: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpWKQvby\file2b38d612fb4'
6: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpWKQvby\file2b38478d289d'


>   myPythonPath <- "G:\\MySoft\\Miniconda\\python.exe"
>   ee_set_pyenv(myPythonPath)
python_env is NULL, RETICULATE_PYTHON_ENV will not be created.
To install this Python environment for use in future sessions, run this function with `install = TRUE`.
> ee_set_pyenv(myPythonPath, install = TRUE)
python_env is NULL, RETICULATE_PYTHON_ENV will not be created.
rgee needs to restart R session to see changes.
Do you want to continues? 

1: yes
2: no

Selection: 2
>   myPythonEnv <- ee_create_pyenv(python_env = "ee")
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: G:\MySoft\MINICO~1\envs\ee

  added / updated specs:
    - python


The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/win-64::ca-certificates-2020.1.1-0
  certifi            pkgs/main/win-64::certifi-2020.4.5.1-py38_0
  openssl            pkgs/main/win-64::openssl-1.1.1g-he774522_0
  pip                pkgs/main/win-64::pip-20.0.2-py38_1
  python             pkgs/main/win-64::python-3.8.2-h5fd99cc_11
  setuptools         pkgs/main/win-64::setuptools-46.1.3-py38_0
  sqlite             pkgs/main/win-64::sqlite-3.31.1-h2a8f88b_1
  vc                 pkgs/main/win-64::vc-14.1-h0510ff6_4
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.16.27012-hf0eaf9b_1
  wheel              pkgs/main/win-64::wheel-0.34.2-py38_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py38_0
  zlib               pkgs/main/win-64::zlib-1.2.11-h62dcd97_4


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.2
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda


#
# To activate this environment, use
#
#     $ conda activate ee
#
# To deactivate an active environment, use
#
#     $ conda deactivate

> myPythonEnv 
[1] "C:\\Anaconda3\\envs\\ee\\python.exe"
> ee_check_python()
(*)  Python version found: G:/MySoft/Miniconda/python.exe v3.7
> 
#RESTART
> library(rgee)
> Sys.getenv("R_USER")
[1] "G:/R_TMP"
> ee_check_python()
(*)  Python version found: C:/Python27/ArcGISx6410.4/python.exe v2.7
Error in ee_check_python() : rgee just run under Python 3.5 >=
In addition: Warning messages:
1: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpwxLaaf\filecdc3cdb25af'
2: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpwxLaaf\filecdcdb01b1f'
3: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpwxLaaf\filecdc160663d6'
4: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpwxLaaf\filecdc6d2d66fe'
5: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpwxLaaf\filecdc632a2049'
6: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpwxLaaf\filecdc57f43e5c'
>   ee_install_python_packages()
Error in ee_check_python(quiet = TRUE) : 
  rgee just run under Python 3.5 >=
In addition: Warning messages:
1: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpwxLaaf\filecdc59b9592'
2: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpwxLaaf\filecdc2a2521b3'
> `

**Comment by csaybar** [comment]
Hi @oleksandrkarasov, could you run in your console:
```r
library(reticulate)
py_config()
```

**Comment by oleksandrkarasov** [comment]
Dear @csaybar 
Please, find it as follows:
`> library(reticulate)
> py_config()
python:         C:/Python27/ArcGISx6410.4/python.exe
libpython:      python27.dll
pythonhome:     C:/Python27/ArcGISx6410.4
version:        2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Python27/ArcGISx6410.4/Lib/site-packages/numpy
numpy_version:  1.9.2

python versions found: 
 G:/MySoft/Miniconda/python.exe
 C:/Python27/ArcGISx6410.4/python.exe
 C:/Python32/python.exe
 C:/Anaconda3/python.exe
 C:/Anaconda3/envs/ee/python.exe
 G:/MySoft/Miniconda/envs/ee/python.exe
Warning messages:
1: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpohdxO1\file24f447f639da'
2: In readLines(rf) :
  incomplete final line found on 'G:/R_TMP\RtmpohdxO1\file24f426af56f6'
> home <- Sys.getenv("HOME")
> renv <- file.path(home, ".Renviron")
> read.table(renv)
                                                       V1
1 RETICULATE_PYTHON="C:\\Anaconda3\\envs\\ee\\python.exe"
> 
`

**Comment by csaybar** [comment]
Really strange, it seems that your path is not good, even you got a warning about it, I am not a good Windows users but the path does not to be something like this?

```r
RETICULATE_PYTHON="C:/Anaconda3/envs/ee/python.exe"
```
Anyway, it is a problem with your PATH environment, maybe eliminating ARCGIS PYTHON PATH manually could help you to fix the error.

**Comment by oleksandrkarasov** [comment]
Dear @csaybar 
When I was installing the Miniconda, I did not add it to the PATH, because it was not recommended:
![image](https://user-images.githubusercontent.com/23281934/80616130-2ff43280-8a49-11ea-8947-c1a625a4cfa4.png)
Do you think re-installation of Miniconda with adding it to PATH may help without threat to ArcGIS?

**Comment by allixender** [comment]
Setting Miniconda on the PATH might not solve the issue. Rather "removing the ArcGis Python from the %PATH% variable, even if only for your R session:

something like:

https://stat.ethz.ch/R-manual/R-devel/library/base/html/Sys.getenv.html

https://stat.ethz.ch/R-manual/R-devel/library/base/html/Sys.setenv.html

## get the full current PATH
orig_path <- Sys.getenv(c("PATH"))

and then something like:

Sys.setenv(PATH = " ... here the stuff from orig_path but without the ArcGIS directories."

**Comment by csaybar** [comment]
This is exactly what does **ee_set_pyenv**!, when you additionally set `install = TRUE` the virtual environment name will be saved in the .Renviron file to use in future sessions.
https://github.com/csaybar/rgee/blob/707db3f64d7e43867bdfb526a09ef954350179b6/R/ee_install.R#L211)

**Comment by csaybar** [comment]
We adapt the installation module now (ee_install_*) to the last version of [reticulate](https://rstudio.github.io/reticulate/news/index.html) which solve several bugs with respect to the use of conda on Windows. If you try again the install, feel free to open the issue!
