### ISSUE TITLE
Add "READY" status to ee_manage_cancel_all_running_task()

### ISSUE THREAD

**Issue by bevingtona** [csaybar/rgee#57]
I accidentally triggered >3000 tasks (oops!). So naturally, I wanted to cancel all of the tasks. I tried to use `ee_manage_cancel_all_running_task()` to cancel them, however this function only cancels the tasks that are currently running (i.e. status = `RUNNING`). Many of the tasks had status `READY` . 

I was able to cancel all >3000 tasks by changing the status in the function from "RUNNING" to "READY".

**Comment by bevingtona** [comment]
This is how I cancelled the tasks: 

``` 
all_task <- ee$data$getTaskList()
running_task <- which(unlist(lapply(all_task, "[[", "state")) == "READY")
running <- all_task[running_task]

for(z in seq_along(running)){
    print(paste(z, z/length(running_task)))
    ee$data$cancelTask(running[[z]][["id"]])}
````

**Comment by csaybar** [comment]
Thanks a lot for reporting this. I will add it in the next release!

**Comment by csaybar** [comment]
Thanks for your contribution. It was added in rgee 0.4.3. If the problem persists, feel free to open the issue again.
