### ISSUE TITLE
mapping over list

### ISSUE THREAD

**Issue by slisovski** [csaybar/rgee#58]
Is there a way to map over a list?
In this scenario, I want to create a FeatureCollection of points:
```
pts = ee$List(list(c(1.5, 31.4), c(1.6, 30.5)))

points = ee$FeatureCollection(pts$map(function(p){
  point = ee$Feature(ee$Geometry$Point(p), {})
  return(point)
}))
```
Is mapping over lists not implemented? Any workarounds?

I could do:
```
pts = ee$List(list(c(1.5, 31.4), c(1.6, 30.5)))$getInfo()
points = ee$FeatureCollection(lapply(pts, function(x) ee$Feature(ee$Geometry$Point(c(x)))))
```
But is that the best solution (rather than mapping)? It is also (obviously) not working with large lists of points when getInfo() reaches the limits.

**Comment by csaybar** [comment]
Hi @slisovski you need to use `ee_pyfun`:

```r
library(rgee)
ee_Initialize()

pts = ee$List(list(c(1.5, 31.4), c(1.6, 30.5)))

points = ee$FeatureCollection(pts$map(ee_pyfunc(function(p){
  point = ee$Feature(ee$Geometry$Point(p), {})
  return(point)
})))

Map$centerObject(points,zoom = 4)
Map$addLayer(points)
```
There are some extra considerations that you need to take account when using GEE with R. See [considerations](https://csaybar.github.io/rgee/articles/considerations.html#the-map-message-error)

**Comment by slisovski** [comment]
Perfect, thanks! I did miss the considerations page.
